// Public roster maintained by the Kolpingtheater website. Login addresses are
// app identifiers; they are not treated as verified mailboxes.
export const organizationMemberSeeds = [
  ['carina', 'Carina', 'Ensemble', 'Drusilla', 'CA'],
  ['elena', 'Elena', 'Ensemble', 'Lucy', 'EL'],
  [
    'fernanda',
    'Fernanda',
    'Ensemble',
    'Tante Heideltraut von Storchensumpf',
    'FE',
  ],
  ['fynn', 'Fynn', 'Ensemble', 'Ensemble', 'FY'],
  ['hendrik', 'Hendrik', 'Ensemble', 'Karl', 'HE'],
  ['jakob', 'Jakob', 'Ensemble', 'Bruno', 'JA'],
  ['jonas', 'Jonas', 'Ensemble', 'Vetter Viktor · Lichttechnik', 'JO'],
  ['jule', 'Jule', 'Ensemble', 'Motte', 'JU'],
  ['julian', 'Julian', 'Ensemble', 'Bühnentechnik', 'JU'],
  ['lena', 'Lena', 'Ensemble', 'Ensemble', 'LE'],
  ['lina', 'Lina', 'Ensemble', 'Fiona', 'LI'],
  ['lina.k', 'Lina K.', 'Ensemble', 'Ensemble', 'LI'],
  ['logge', 'Logge', 'Ensemble', 'Bote / Diener · Website', 'LO'],
  ['louis', 'Louis', 'Ensemble', 'Graf Thaddäus von Falkenstein', 'LO'],
  ['marcella', 'Marcella', 'Ensemble', 'Suzie', 'MA'],
  ['max', 'Max', 'Ensemble', 'Ensemble', 'MA'],
  ['maximilian', 'Maximilian', 'Ensemble', 'Ensemble', 'MA'],
  ['nela', 'Nela', 'Ensemble', 'Felia', 'NE'],
  ['nele', 'Nele', 'Ensemble', 'Prinzessin Iset', 'NE'],
  ['niko', 'Niko', 'Ensemble', 'Praktikant Emil', 'NI'],
  ['nora', 'Nora', 'Ensemble', 'Ensemble', 'NO'],
  ['raphael', 'Raphael', 'Ensemble', 'Diener', 'RA'],
  ['sebastian', 'Sebastian', 'Ensemble', 'Butler Wilson / Regie', 'SE'],
  ['sophie', 'Sophie', 'Ensemble', 'Mia', 'SO'],
  ['theresa', 'Theresa', 'Ensemble', 'Clara', 'TH'],
  ['till', 'Till', 'Ensemble', 'Herr Schniebli', 'TI'],
  ['tobias', 'Tobias', 'Ensemble', 'Jacques', 'TO'],
  ['vanessa', 'Vanessa', 'Ensemble', 'Ensemble', 'VA'],
  ['yunus', 'Yunus', 'Ensemble', 'Dr. Adrian Düsterwald', 'YU'],
  ['cathrin', 'Cathrin', 'Kostümteam', 'Kostüme', 'CA'],
  ['christian', 'Christian', 'Technik', 'Bühnentechnik · Videotechnik', 'CH'],
  ['daniel', 'Daniel', 'Technik', 'Lichttechnik', 'DA'],
  ['elea', 'Elea', 'Technik', 'Bühnentechnik', 'EL'],
  ['emilia', 'Emilia', 'Technik', 'Bühnentechnik', 'EM'],
  ['florian', 'Florian', 'Technik', 'Lichttechnik', 'FL'],
  ['julian.technik', 'Julian (Technik)', 'Technik', 'Bühnentechnik', 'JU'],
  ['leo', 'Leo', 'Technik', 'Bühnentechnik · Fotografie', 'LE'],
  ['philipp', 'Philipp', 'Technik', 'Bühnentechnik', 'PH'],
  ['maren', 'Maren', 'Technik', 'Bühnentechnik', 'MA'],
  ['wolfgang', 'Wolfgang', 'Technik', 'Tontechnik', 'WO'],
  ['ursula', 'Ursula', 'Technik', 'Tontechnik', 'UR'],
].map(([login, name, groupName, roleName, initials]) => ({
  email: `${login}@kolpingtheater-ramsen.de`,
  name,
  groupName,
  roleName,
  initials,
  active: 1,
  profileRole: name === 'Yunus' || name === 'Sebastian' ? 'admin' : 'member',
}));

export const legacyDemoEmails = [
  'technik@kolpingtheater-ramsen.de',
  'noah.becker@kolpingtheater-ramsen.de',
  'mia.wagner@kolpingtheater-ramsen.de',
  'jonas.hoffmann@kolpingtheater-ramsen.de',
  'sarah.klein@kolpingtheater-ramsen.de',
  'tobias.hartmann@kolpingtheater-ramsen.de',
  'emilia.schmitt@kolpingtheater-ramsen.de',
  'felix.braun@kolpingtheater-ramsen.de',
];
